export const state = () => ({
  selectedRegion: '',
  filters: [],
  places: [],
  appliedFilters: {},
  place: {},
  raiting: null,
  reviews: [],
  pictures: [],
  route: [],
  routes: [],
  booking: [],
  routeInfo: {},
  pagination: {},
  page: 1,
  isLastPage: false,
  isLastRoutesPage: false,
})